In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4]
my_list2 = my_list * 2
my_array = np.array([1,2,3,4])
my_array *= 2
print(my_list)
print(my_array)
print(my_array.ndim)

[1, 2, 3, 4]
[2 4 6 8]
1


# **Multidimensional arrays**
```
array = np.array('A') -> array.ndim = 0
```

In [4]:
array2 = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]], [[19,20,21],[22,23,24],[25,26,27]]])
print(array2)
print(array2.ndim)

print(array2[0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(array2[0][1])
print(array2[0,0,1])

[4 5 6]
2


In [6]:
array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]
])
print(array.ndim)
my_name = array[2,0,1] + array[0,2,1] + array[2,0,2] + array[2,2,0] + array[0,1,1] + array[1,1,1]
print(my_name)

3
THUYEN


# **Slicing**
### Access the rows
```
array[start:end:step]
```
```array[::-1]```  -> all the row reverse
```array[::-2]```  -> all the second rows in reverse
### Access the cols
```array[:,0]``` -> col 0


In [7]:
slice_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(f'All the elements in reverse order: {slice_array[::-1]}')

All the elements in reverse order: [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [8]:
print(f'All elements in column 1: {slice_array[:,1 ]}')
print(f'First two rows and first two cols: {slice_array[0:2,0:2]}')

All elements in column 1: [ 2  6 10 14]
First two rows and first two cols: [[1 2]
 [5 6]]


# **Arithmetic**
### Scalar Arithmetic

In [9]:
sca_ari_array = np.array([1,2,3])
print(sca_ari_array + 1)
print(sca_ari_array - 2)
print(sca_ari_array * 3)
print(sca_ari_array / 4)
print(sca_ari_array ** 3)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[ 1  8 27]


### Vectorized math func

In [10]:
vec_math_array = np.array([1.01, 2.5, 3.99])

print(np.sqrt(vec_math_array))
print(np.round(vec_math_array)) # normal round
print(np.floor(vec_math_array)) # round down
print(np.ceil(vec_math_array)) # round up
print(np.pi)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [11]:
# Calculate area when we have an array of radius
radii = np.array([1,2,3])
print(f'Area of an array of radius: {np.pi * radii ** 2}')

Area of an array of radius: [ 3.14159265 12.56637061 28.27433388]


### Elemet-wise arithmetic

In [12]:
ele_array1 = np.array([1,2,3])
ele_array2 = np.array([4,5,6])
print(ele_array1 + ele_array2)
print(ele_array1 - ele_array2)
print(ele_array1 * ele_array2)
print(ele_array1 / ele_array2)
print(ele_array1 ** ele_array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


### Comparison operators

In [13]:
scores = np.array([91, 55, 100, 73, 82, 64])
print(scores >= 60)

scores[scores <= 60] = 0
print(scores)

[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


# **Broadcasting**
Allow numpy to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape

In [14]:
br_array1 = np.array([[1,2,3,4]])
print(f'Dimension of array1: {br_array1.ndim}')
br_array2 = np.array([[1], [2], [3], [4]])
print(f'Dimension of array2: {br_array2.ndim}')
print(f'Shape of array1: {br_array1.shape}')
print(f'Shape of array2: {br_array2.shape}')

Dimension of array1: 2
Dimension of array2: 2
Shape of array1: (1, 4)
Shape of array2: (4, 1)


In [15]:
print(br_array1 * br_array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [16]:
bro_ex_array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
bro_ex_array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(bro_ex_array1 * bro_ex_array2)
bro_ex_combine = bro_ex_array1 * bro_ex_array2
bro_ex_combine2 = bro_ex_array2 * bro_ex_array1
print(bro_ex_array1.shape)
print(bro_ex_combine2.shape)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
(1, 10)
(10, 10)


# **Aggregate functions**
Summarize data and typically return a single value

In [17]:
agg_array1 = np.array([[1,2,3,4,5],
                       [6,7,8,9,10]])
print(f'Sum of the array: {np.sum(agg_array1)}')
print(f'Mean of the array: {np.mean(agg_array1)}')
print(f'Std of the array: {np.std(agg_array1)}')
print(f'Var of the array: {np.var(agg_array1)}')
print(f'Min of the array: {np.min(agg_array1)}')
print(f'Max of the array: {np.max(agg_array1)}')
print(f'Index of the minimum value: {np.argmin(agg_array1)}')
print(f'Index of the maximum value: {np.argmax(agg_array1)}')

Sum of the array: 55
Mean of the array: 5.5
Std of the array: 2.8722813232690143
Var of the array: 8.25
Min of the array: 1
Max of the array: 10
Index of the minimum value: 0
Index of the maximum value: 9


axis=0 -> all columns
axis=1 -> all rows

In [18]:
print(f'Sums of elements in rows: {np.sum(agg_array1, axis=1)}')
print(f'Sums of elements in cols: {np.sum(agg_array1, axis=0)}')

Sums of elements in rows: [15 40]
Sums of elements in cols: [ 7  9 11 13 15]


# **Filtering**
Refers to the process of selecting elements from an array that match a given condition

In [19]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
print(f'There are {len(teenagers)} teenagers: {teenagers}')

adults = ages[(ages >= 18) & (ages < 65)]
print(f'There are {len(adults)} adults: {adults}')

seniors = ages[ages >= 65]
print(f'There are {len(seniors)} seniors: {seniors}')

There are 3 teenagers: [17 16 15]
There are 11 adults: [21 19 20 30 18 39 22 18 19 20 21]
There are 2 seniors: [65 99]


In [21]:
wadults = np.where(ages >= 18, ages, 0)
print(wadults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [31]:
rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=101, size=3))

[48 52 76]


In [32]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]
